# Jekyll
permalink: /blog/:year/:month/:day/:title
# permalink: /blog/:title/
paginate: 10
max_blog_list: 5
name: Stephen
baseurl: "http://127.0.0.1:4000"
exclude: ["start_development", ".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]

twitter: https://twitter.com/swmcc
linkedin: https://uk.linkedin.com/in/theonlystephen
github: https://github.com/swmcc
email: stephen@sixdegreelabs.com