# Jekyll
permalink: /blog/:year/:month/:day/:title
paginate: 10
exclude: [less]
name: Stephen 
baseurl:  
exclude: ["start_development", ".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
