permalink: /:title
paginate_path: "/blog/page:num"
paginate: 8
baseurl: ""

title: The Only Stephen | Portfolio & Blog
description: > # this means to ignore newlines until "baseurl:"
  The portfolio and blog of Stephen, a developer based in Belfast, Northern Ireland

name: Stephen McCullough
twitter: https://twitter.com/swmcc
linkedin: https://uk.linkedin.com/in/theonlystephen
github: https://github.com/swmcc
email: me@theonlystephen.com

exclude: ["start_development", ".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
